.PHONY: *

# Execute the "targets" in this file with `make <target>` e.g., `make test`.

# You can also run multiple in sequence, e.g. `make clean lint test serve-coverage-report`

run:
	bash run.sh run

clean:
	bash run.sh clean

help:
	bash run.sh help

install:
	bash run.sh install

lint:
	bash run.sh lint

lint-ci:
	bash run.sh lint:ci

test-ci:
	bash run.sh test:ci

test-quick:
	bash run.sh test:quick

test:
	bash run.sh run-tests
