"""Initial

Revision ID: 0b6d43fcaefc
Revises: 
Create Date: 2025-03-29 01:24:08.824261

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b6d43fcaefc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subjects_fts_data')
    op.drop_table('chapters_fts_data')
    op.drop_table('subjects_fts_idx')
    op.drop_table('chapters_fts_docsize')
    op.drop_table('_alembic_tmp_quiz_signups')
    op.drop_table('quizzes_fts')
    op.drop_table('chapters_fts_idx')
    op.drop_table('quizzes_fts_data')
    op.drop_table('quizzes_fts_idx')
    op.drop_table('users_fts')
    op.drop_table('quizzes_fts_config')
    op.drop_table('users_fts_data')
    op.drop_table('users_fts_idx')
    op.drop_table('chapters_fts')
    op.drop_table('subjects_fts')
    op.drop_table('users_fts_docsize')
    op.drop_table('users_fts_config')
    op.drop_table('subjects_fts_config')
    op.drop_table('quizzes_fts_docsize')
    op.drop_table('subjects_fts_docsize')
    op.drop_table('chapters_fts_config')
    with op.batch_alter_table('question_attempts', schema=None) as batch_op:
        batch_op.alter_column('selected_option',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question_attempts', schema=None) as batch_op:
        batch_op.alter_column('selected_option',
               existing_type=sa.INTEGER(),
               nullable=False)

    op.create_table('chapters_fts_config',
    sa.Column('k', sa.NullType(), nullable=False),
    sa.Column('v', sa.NullType(), nullable=True),
    sa.PrimaryKeyConstraint('k')
    )
    op.create_table('subjects_fts_docsize',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('sz', sa.BLOB(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quizzes_fts_docsize',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('sz', sa.BLOB(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subjects_fts_config',
    sa.Column('k', sa.NullType(), nullable=False),
    sa.Column('v', sa.NullType(), nullable=True),
    sa.PrimaryKeyConstraint('k')
    )
    op.create_table('users_fts_config',
    sa.Column('k', sa.NullType(), nullable=False),
    sa.Column('v', sa.NullType(), nullable=True),
    sa.PrimaryKeyConstraint('k')
    )
    op.create_table('users_fts_docsize',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('sz', sa.BLOB(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subjects_fts',
    sa.Column('name', sa.NullType(), nullable=True),
    sa.Column('description', sa.NullType(), nullable=True)
    )
    op.create_table('chapters_fts',
    sa.Column('name', sa.NullType(), nullable=True),
    sa.Column('description', sa.NullType(), nullable=True)
    )
    op.create_table('users_fts_idx',
    sa.Column('segid', sa.NullType(), nullable=False),
    sa.Column('term', sa.NullType(), nullable=False),
    sa.Column('pgno', sa.NullType(), nullable=True),
    sa.PrimaryKeyConstraint('segid', 'term')
    )
    op.create_table('users_fts_data',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('block', sa.BLOB(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quizzes_fts_config',
    sa.Column('k', sa.NullType(), nullable=False),
    sa.Column('v', sa.NullType(), nullable=True),
    sa.PrimaryKeyConstraint('k')
    )
    op.create_table('users_fts',
    sa.Column('username', sa.NullType(), nullable=True),
    sa.Column('full_name', sa.NullType(), nullable=True),
    sa.Column('email', sa.NullType(), nullable=True)
    )
    op.create_table('quizzes_fts_idx',
    sa.Column('segid', sa.NullType(), nullable=False),
    sa.Column('term', sa.NullType(), nullable=False),
    sa.Column('pgno', sa.NullType(), nullable=True),
    sa.PrimaryKeyConstraint('segid', 'term')
    )
    op.create_table('quizzes_fts_data',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('block', sa.BLOB(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chapters_fts_idx',
    sa.Column('segid', sa.NullType(), nullable=False),
    sa.Column('term', sa.NullType(), nullable=False),
    sa.Column('pgno', sa.NullType(), nullable=True),
    sa.PrimaryKeyConstraint('segid', 'term')
    )
    op.create_table('quizzes_fts',
    sa.Column('name', sa.NullType(), nullable=True),
    sa.Column('remarks', sa.NullType(), nullable=True)
    )
    op.create_table('_alembic_tmp_quiz_signups',
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('quiz_id', sa.INTEGER(), nullable=False),
    sa.Column('signup_time', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['quiz_id'], ['quizzes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'quiz_id')
    )
    op.create_table('chapters_fts_docsize',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('sz', sa.BLOB(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subjects_fts_idx',
    sa.Column('segid', sa.NullType(), nullable=False),
    sa.Column('term', sa.NullType(), nullable=False),
    sa.Column('pgno', sa.NullType(), nullable=True),
    sa.PrimaryKeyConstraint('segid', 'term')
    )
    op.create_table('chapters_fts_data',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('block', sa.BLOB(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subjects_fts_data',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('block', sa.BLOB(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
