"""Update database schema

Revision ID: 4cc6fd5479f8
Revises: 6ee5aa684a60
Create Date: 2025-03-27 18:10:26.052542

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4cc6fd5479f8'
down_revision = '6ee5aa684a60'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_score', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('number_of_correct_answers', sa.Integer(), nullable=False))
        batch_op.drop_column('total_score')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_score', sa.INTEGER(), nullable=False))
        batch_op.drop_column('number_of_correct_answers')
        batch_op.drop_column('user_score')

    # ### end Alembic commands ###
