"""Added

Revision ID: 6ee5aa684a60
Revises: 
Create Date: 2025-03-27 13:50:35.852572

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ee5aa684a60'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz_signups', schema=None) as batch_op:
        batch_op.alter_column('signup_time',
               existing_type=sa.DATETIME(),
               nullable=False)

    with op.batch_alter_table('scores', schema=None) as batch_op:
        batch_op.drop_index('ix_scores_timestamp')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scores', schema=None) as batch_op:
        batch_op.create_index('ix_scores_timestamp', ['timestamp'], unique=False)

    with op.batch_alter_table('quiz_signups', schema=None) as batch_op:
        batch_op.alter_column('signup_time',
               existing_type=sa.DATETIME(),
               nullable=True)

    # ### end Alembic commands ###
